project_id = "kywmhuubbsvclkorxrse"

[functions.annotate-pos]
verify_jwt = false

[functions.annotate-semantic]
verify_jwt = false

[functions.send-critical-alert]
verify_jwt = false

[functions.refine-tagset-suggestions]
verify_jwt = false

[functions.calculate-priority-score]
verify_jwt = false